GET https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=86bdm842ht73vz&redirect_uri=http://localhost:3000/linkedin&state=fooobar&scope=r_liteprofile%20r_emailaddress
https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=86bdm842ht73vz&redirect_uri=http://localhost:3000/linkedin&state=fooobar&scope=r_liteprofile%20r_emailaddress



POST /oauth/v2/accessToken HTTP/1.1
Host: www.linkedin.com
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=AQQYj3IvwNAPWsInUJFsttU1KQUxQKh_-l7E8FuLDMi4YIZCOKelqXToCO-TFWKbDXXDA4VxobXA656DH5RwujvwH9uw6XObX36ZCAeZo9TuZdWPMI35aINBwOuoMPhPkzhDVZekGb_8OOM9w0E9Z6Cw-Fh9O3NFnoT5c5GyivTl8qo-wtl-LACK_za0YPMw18wq_boMraoId7sUAF8&redirect_uri=https://hnmeddcfcpkhfppcpngghaghelcefjip.chromiumapp.org/loadtoken.html&client_id=86bdm842ht73vz&client_secret=VHQ3HvGnIPgPHR82


fetch("https://www.linkedin.com/oauth/v2/accessToken", {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: "grant_type=authorization_code&code=AQQDW3zz6H_XOF3GTuwV_ctn6L_ue575orA_HZP8WGUhVB63O7locGilxeQuP2R6_YM4pRHnPO2MUeiV-8U3Bate1XIzRGZ5kyX1YXcVgK-msbKWoiIvSUdvPOb9pUr9rZV2IUTmPfil3agkD6sAG0IY8IvnBwZ1gEwomuL78UUBHKTqt10b9rI9K0Kr7k9vbSFSgNXS4bvr2lw3qGE&redirect_uri=https://hnmeddcfcpkhfppcpngghaghelcefjip.chromiumapp.org/loadtoken.html&client_id=86bdm842ht73vz&client_secret=VHQ3HvGnIPgPHR82",
  }).then(res=> res.json()).then(res => console.log(res));

https://www.linkedin.com/oauth/v2/accessToken?grant_type=authorization_code&code=AQQDW3zz6H_XOF3GTuwV_ctn6L_ue575orA_HZP8WGUhVB63O7locGilxeQuP2R6_YM4pRHnPO2MUeiV-8U3Bate1XIzRGZ5kyX1YXcVgK-msbKWoiIvSUdvPOb9pUr9rZV2IUTmPfil3agkD6sAG0IY8IvnBwZ1gEwomuL78UUBHKTqt10b9rI9K0Kr7k9vbSFSgNXS4bvr2lw3qGE&redirect_uri=https://hnmeddcfcpkhfppcpngghaghelcefjip.chromiumapp.org/loadtoken.html&client_id=86bdm842ht73vz&client_secret=VHQ3HvGnIPgPHR82